---
title: Jon Virga
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
    description: Some of my thoughts and ideas
    feature_text: Welcome to my blog
    feature_image: https://picsum.photos/2560/600?image=866
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/default-social-image.png"
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- ".jekyll-cache"
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jemoji
- jekyll-remote-theme
- jekyll-include-cache
paginate: 3
paginate_path: blog/page:num
author: Jon Virga
social:
  name: Jon Virga
  links:
  - https://www.facebook.com/jonvirga
  - https://www.linkedin.com/in/jonathanvirga
  - https://github.com/jjjvvvvv
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
lang: en-US
logo: "/assets/logos/logo.svg"
description: Alembic is a starting point for Jekyll projects. Rather than starting
  from scratch, this boilerplate is designed to get the ball rolling immediately
baseurl: "/Portfolio"
url: https://jjjvvvvv.github.io
repo: https://github.com/jjjvvvvv/porfolio
email: Jonathanvrg554@gmail.com
css_inline: true
favicons:
  '16': "/assets/logos/logo@16px.png"
  '32': "/assets/logos/logo@32px.png"
  '96': "/assets/logos/logo@96px.png"
  '120': "/assets/logos/logo@120px.png"
  '144': "/assets/logos/logo@144px.png"
  '180': "/assets/logos/logo@180px.png"
  '512': "/assets/logos/logo@512px.png"
  '1024': "/assets/logos/logo@1024px.png"
navigation_header:
- title: Home
  url: "/"
- title: Elements
  url: "/elements/"
- title: Blog
  url: "/blog/"
- title: Categories
  url: "/categories/"
- title: Search
  url: "/search/"
social_links:
  LinkedIn: https://www.linkedin.com/in/jonvirga
  GitHub: https://github.com/jjjvvvvv
sharing_links:
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
navigation_footer:
- title: Thanks for stopping by!
  remote_theme: daviddarnes/alembic@main
